name: shaman-ai-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243

  - pip:
    - stable-baselines3[extra]
    - lxml
    - tqdm
    - seaborn
    - pillow
